# Task requirments  

Build a Decision tree classifier to predict wheather a customer will buy a product or service based on their demographic and behaviorial data.

data set used = ( https://archive.ics.uci.edu/dataset/222/bank+marketing )

About data = The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution.

Meta data = ( 45211 rows )  and ( 17 Columns )

# Loading data set and performing Some EDA

In [87]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv(r"C:\Users\reals\Desktop\prodigy_task_1\task 03\bank-full.csv")
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [7]:
df.shape

(45211, 17)

In [8]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [9]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [19]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [59]:
# Creating X and Y variables 
x = df.drop(columns={'y'})
y = df['y']

In [60]:
x.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')

# Label Encoding the Categorical data 

In [62]:
le = LabelEncoder()
x['age'] = le.fit_transform(x['age'])
x['job'] = le.fit_transform(x['job'])
x['marital'] = le.fit_transform(x['marital'])
x['education'] = le.fit_transform(x['education'])
x['default'] = le.fit_transform(x['balance'])
x['housing'] = le.fit_transform(x['housing'])
x['loan'] = le.fit_transform(x['loan'])
x['contact'] = le.fit_transform(x['contact'])
x['day'] = le.fit_transform(x['day'])
x['month'] = le.fit_transform(x['month'])
x['duration'] = le.fit_transform(x['duration'])
x['campaign'] = le.fit_transform(x['campaign'])
x['pdays'] = le.fit_transform(x['pdays'])
x['previous'] = le.fit_transform(x['previous'])
x['poutcome'] = le.fit_transform(x['poutcome'])

In [63]:
x

age  job  marital  education  default  balance  housing  loan  contact  \
0       40    4        1          2     3036     2143        1     0        2   
1       26    9        2          1      945       29        1     0        2   
2       15    2        1          1      918        2        1     1        2   
3       29    1        1          3     2420     1506        1     0        2   
4       15   11        2          3      917        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   33    9        1          2     1741      825        0     0        0   
45207   53    5        0          0     2639     1729        0     0        0   
45208   54    5        1          1     5455     5715        0     0        0   
45209   39    1        1          1     1584      668        0     0        1   
45210   19    2        1          1     3779     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  
0        4      8       261         0      0         0         3  
1        4      8       151         0      0         0         3  
2        4      8        76         0      0         0         3  
3        4      8        92         0      0         0         3  
4        4      8       198         0      0         0         3  
...    ...    ...       ...       ...    ...       ...       ...  
45206   16      9       975         2      0         0         3  
45207   16      9       456         1      0         0         3  
45208   16      9      1116         4    181         3         2  
45209   16      9       508         3      0         0         3  
45210   16      9       361         1    185        11         1  

[45211 rows x 16 columns]

In [64]:
y = le.fit_transform(y)

In [65]:
y

array([0, 0, 0, ..., 1, 0, 0])

# Splitting the data to train test split

In [66]:
X_train , X_test , Y_train , Y_test = train_test_split(x,y,test_size=0.2,random_state=20)

In [88]:
X_train

age  job  marital  education  default  balance  housing  loan  contact  \
31214   19    9        1          2     1465      549        0     0        0   
12151   15    0        1          1      805     -111        1     1        2   
19014   41    5        1          1     6728    12438        0     0        0   
6377    27    2        1          0      816     -100        1     0        2   
33726   12    8        2          0     2441     1527        0     0        1   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
31962   13    1        1          1     2322     1406        1     1        0   
23452   41    4        1          2     2498     1585        0     0        1   
23775   21    4        1          2      899      -17        1     1        0   
37135   14    9        1          1      279     -684        1     0        0   
27098   35    1        1          1     2685     1777        1     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  
31214    1      7       239         0      0         0         3  
12151   19      6        12         2      0         0         3  
19014    4      1        91         0      0         0         3  
6377    26      8       240         5      0         0         3  
33726   21      0        94         6      0         0         3  
...    ...    ...       ...       ...    ...       ...       ...  
31962   12      0      1082         1      0         0         3  
23452   27      1        91         4      0         0         3  
23775   27      1       906         0      0         0         3  
37135   12      8        11         7    296         3         1  
27098   20      9       796         4    151         1         0  

[36168 rows x 16 columns]

In [90]:
X_test

age  job  marital  education  default  balance  housing  loan  contact  \
14458   14    9        2          2     1334      418        0     1        0   
42532   14    0        2          1     1047      131        1     0        0   
15048   12    7        1          1     2202     1286        1     1        0   
40121    2    0        2          1     1252      336        0     1        0   
27812   10   10        2          1      939       23        0     0        0   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
12327   10    1        1          0     1618      702        1     0        2   
18978   29    2        1          1     1234      318        0     0        0   
4078    30    9        1          1     1438      522        1     0        2   
26474   12    7        0          1      994       78        1     0        0   
4330    27    4        1          3     6369     9051        1     0        2   

       day  month  duration  campaign  pdays  previous  poutcome  
14458   13      5       138         2      0         0         3  
42532   20      2       322         0    186         1         2  
15048   16      5       544         0      0         0         3  
40121    4      6       133         0      0         0         3  
27812   27      4       154         0      0         0         3  
...    ...    ...       ...       ...    ...       ...       ...  
12327   25      6       318         1      0         0         3  
18978    3      1       299         1      0         0         3  
4078    18      8        71         0      0         0         3  
26474   19      9       147         1      0         0         3  
4330    18      8       124        47      0         0         3  

[9043 rows x 16 columns]

In [91]:
Y_train

array([1, 0, 0, ..., 1, 0, 1])

In [92]:
Y_test

array([0, 1, 0, ..., 0, 0, 0])

# Creating a model Using Decision Tree Classifier

In [67]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [68]:
model.score(X_test, Y_test)

0.8771425411920822

In [69]:
model.predict(X_test.iloc[0].values.reshape(1, -1))

c:\Users\reals\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [86]:
model.predict([[14,0,2,1,1047,131,1,0,0,20,2,322,0,186,1,2]])

c:\Users\reals\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])